<a href="https://colab.research.google.com/github/arcyda/DeepLearningHandsOn/blob/main/vector_basic_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

generate 1-d array

reshape(): 改变张量的形状，但是不改变元素的数量和元素值

In [ ]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

生成全0

生成全1

In [ ]:
torch.zeros(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

创建数组

进行+ - * /，每个位置的元素进行加减乘除

In [ ]:
x = torch.tensor([1.0, 2, 4, 8]) # 因为1.0，所以创建的为浮点数组
y = torch.tensor([2, 2, 2, 2]) #创建整型数组
x + y, x - y, x * y, x / y, x ** y  # **是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

torch.cat(rec1, rec2, dim)把多个张量/矩阵连在一起

In [ ]:
X = torch.arange(12).reshape(3,4)
Y = torch.tensor([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1) # dim = 0,对于结果来说，增加行数； dim = 1; 增加列数

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]]), tensor([[ 0,  1,  2,  3,  1,  1,  1,  1],
         [ 4,  5,  6,  7,  2,  2,  2,  2],
         [ 8,  9, 10, 11,  3,  3,  3,  3]]))

通过逻辑运算符构建二维张量

In [ ]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


矩阵的运算:单个矩阵求和，得到一个数值

In [ ]:
X.sum()

tensor(66)

注意广播机制：假设A:1*3矩阵, B: 3*2矩阵，但可以执行A+B，得到的结果3 * 3矩阵，A，B会被扩张，扩张位置补零

元素访问，元素修改：根据下表

-1  最后一个位置

1:3 前闭后开

In [ ]:
Y[-1], Y[1:3] #选择"行"

(tensor([3, 3, 3, 3]), tensor([[2, 2, 2, 2],
         [3, 3, 3, 3]]))

In [ ]:
Y[:, -1] #选择"列"

tensor([1, 2, 3])

In [ ]:
Y[2, 2] = 9
Y

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 9, 3]])

矩阵运算时，减小内存操作的方法

如果 X = X + Y, 会给X重新分配内存

如果 X += Y 或者 X[:] = X + Y,则不重新分配内存

torch张量 转变为 NumPy张量

In [ ]:
A = Y.numpy()
B = torch.tensor(A)
print(A)
type(A), type(B)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 9 3]]


(numpy.ndarray, torch.Tensor)

将1*1的张量转化为标量 item()

In [ ]:
a = torch.tensor(3.5)
b = a.item()
b, type(b), a, type(a)

(3.5, float, tensor(3.5000), torch.Tensor)